#!/bin/bash

## iRedmail Armbian ##
wget https://github.com/iredmail/iRedMail/releases/download/1.3.1/iRedMail-1.3.1.tar.gz && \
wget http://www.axis.cz/linux/debian/pool/axis/a/axis-archive-keyring/axis-archive-keyring_2014.06.21.a_all.deb && \
tar zxf iRedMail-1.3.1.tar.gz && dpkg -i axis-archive-keyring_2014.06.21.a_all.deb && \
sed -i 's/enabled=1/enabled=0/g' /root/iRedMail-1.3.1/functions/packages.sh && \
mv /etc/profile.d/armbian-check-first-login.sh /etc/profile.d/armbian-check-first-login.bak && \
echo "deb http://www.axis.cz/linux/debian buster sogo-v4" >> /etc/apt/sources.list && \
cd /root/iRedMail-1.3.1 && \
USE_EXISTING_MYSQL='YES' \
    MYSQL_SERVER_ADDRESS='db.mizutech.id' \
    MYSQL_SERVER_PORT='3306' \
    MYSQL_ROOT_USER='root' \
    MYSQL_ROOT_PASSWD='admin123' \
    MYSQL_GRANT_HOST='usagi.mizutech.id' \
    bash iRedMail.sh
